version : '3'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/user/src/app
    ports:
      - 3000:5000
    depends_on:
      - sessioncache
      - backend
    environment:
      PORT: 5000
      REDIS_HOST: sessioncache
      REDIS_PORT: 6379
      BACKENDBASEURL: backend
      BACKENDPORT: 5001
      DB_CONNECTION: 
  
  backend:
    build: ./backend
    volumes:
      - ./backend:/user/src/app
    environment: 
      DB_CONNECTION: 
      PORT: 5001

  sessioncache:
    image: redis:latest
    ports:
      - 6379:6379
