apiVersion: v1
kind: Secret
metadata:
  name: secretkeystore
type: Opaque
data:
  googlesigninid: 
  paypalclientid:
  dbconnection: 
  iexcloudtoken: 
  backenddbconn: 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 134501469378.dkr.ecr.us-east-1.amazonaws.com/earnprosper/backend:latest
        env:
        - name: PORT
          value: "5001"
        - name: IEX_CLOUD_TOKEN
          valueFrom:
           secretKeyRef:
            name: secretkeystore
            key: iexcloudtoken
        - name: DB_CONNECTION
          valueFrom:
           secretKeyRef:
            name: secretkeystore
            key: backenddbconn
        ports:
        - containerPort: 5001
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: regcred
---

apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 134501469378.dkr.ecr.us-east-1.amazonaws.com/earnprosper/frontend:latest
        env:
        - name: BACKENDBASEURL
          value: backend-svc
        - name: BACKENDPORT
          value: "5001"
        - name: PORT
          value: "5000"
        - name: REDIS_HOST
          value: sessioncache-svc
        - name: REDIS_PORT
          value: "6379"
        - name: DB_CONNECTION
          valueFrom:
           secretKeyRef:
            name: secretkeystore
            key: dbconnection
        - name: GOOGLE_SIGNIN_CLIENT_ID
          valueFrom:
           secretKeyRef:
            name: secretkeystore
            key: googlesigninid
        - name: PAYPAL_CLIENT_ID
          valueFrom:
           secretKeyRef:
            name: secretkeystore
            key: paypalclientid
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: regcred
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sessioncache
  labels:
    app: sessioncache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sessioncache
  template:
    metadata:
      labels:
        app: sessioncache
    spec:
      containers:
      - name: sessioncache
        image: redis:latest
        ports:
        - containerPort: 6379
        imagePullPolicy: IfNotPresent
---

apiVersion: v1
kind: Service
metadata:
  name: sessioncache-svc
spec:
  selector:
    app: sessioncache
  ports:
  - protocol: TCP
    port: 6379




